Server:
  Port: 5555
  RunMode: debug
Logger:
  FilePath: ../logs/logs.log
  Encoding: json
  Level: debug
  Logger: zaplogger
Cors:
  AllowOrigins: "*"
Postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  DbName: test
  SslMode: disable
  MaxIdleConns: 5
  MaxOpenConns: 100
  ConnMaxLifetime: 5
Redis:
  Host: redis_container
  Port: 6379
  Password: password
  Db: 0
  DialTimeout: 5
  ReadTimeout: 5
  WriteTimeout: 5
  PoolSize: 10
  PoolTimeout: 15
  IdleCheckFrequency: 500